//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class UserConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserConfiguration defaultInstance = ((UserConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserConfiguration())));
        
        public static UserConfiguration Default {
            get {
                return defaultInstance;
            }
        }
    }
}
